<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CatMunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('cat_municipios')->insert([
            ['nom_mpio' => 'Acuitzio', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Aguililla', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Álvaro Obregón', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Angamacutiro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Angangueo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Apatzingán', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Aporo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Aquila', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Ario', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Arteaga', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Briseñas', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Buenavista', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Carácuaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Coahuayana', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Coalcomán de Vázquez Pallares', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Coeneo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Contepec', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Copándaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Cotija', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Cuitzeo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Charapan', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Charo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Chavinda', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Cherán', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Chilchota', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Chinicuila', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Chucándiro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Churintzio', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Churumuco', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Ecuandureo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Epitacio Huerta', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Erongarícuaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Gabriel Zamora', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Hidalgo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'La Huacana', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Huandacareo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Huaniqueo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Huetamo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Huiramba', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Indaparapeo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Irimbo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Ixtlán', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Jacona', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Jiménez', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Jiquilpan', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Juárez', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Jungapeo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Lagunillas', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Madero', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Maravatío', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Marcos Castellanos', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Lázaro Cárdenas', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Morelia', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Morelos', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Múgica', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Nahuatzen', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Nocupétaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Nuevo Parangaricutiro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Nuevo Urecho', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Numarán', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Ocampo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Pajacuarán', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Panindícuaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Parácuaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Paracho', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Pátzcuaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Penjamillo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Peribán', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'La Piedad', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Purépero', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Puruándiro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Queréndaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Quiroga', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Cojumatlán de Régules', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Los Reyes', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Sahuayo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'San Lucas', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Santa Ana Maya', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Salvador Escalante', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Senguio', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Susupuato', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tacámbaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tancítaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tangamandapio', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tangancícuaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tanhuato', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Taretan', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tarímbaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tepalcatepec', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tingambato', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tingüindín', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tiquicheo de Nicolás Romero', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tlalpujahua', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tlazazalca', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tocumbo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tumbiscatío', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Turicato', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tuxpan', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tuzantla', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tzintzuntzan', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Tzitzio', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Uruapan', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Venustiano Carranza', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Villamar', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Vista Hermosa', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Yurécuaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Zacapu', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Zamora', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Zináparo', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Zinapécuaro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'Ziracuaretiro', 'entidad_fed_id' => 16],
            ['nom_mpio' => 'José Sixto Verduzco', 'entidad_fed_id' => 16],
        ]);
    }
}
